"""Generate README.md, a GitHub Actions workflow, .gitignore, and example
tfvars from a generation — all deterministic text."""

from __future__ import annotations

from app.services.scaffold import hcl_summary

GITIGNORE = """\
# Terraform
.terraform/
.terraform.lock.hcl
*.tfstate
*.tfstate.*
crash.log
crash.*.log

# Variable files with real values (keep the .example)
*.tfvars
!*.tfvars.example
*.auto.tfvars

# Plan output & overrides
*.tfplan
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Sensitive
*.pem
*.key
.env
"""

CI_WORKFLOW = """\
name: Terraform

on:
  pull_request:
    paths: ["**.tf", "**.tfvars.example"]
  push:
    branches: [main]
    paths: ["**.tf"]

permissions:
  contents: read

jobs:
  terraform:
    name: fmt / init / validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      # Optional: uncomment to run `plan` on PRs. Requires AWS credentials in
      # repo secrets and a real backend/state — remove -backend=false above.
      # - name: Terraform plan
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: us-east-1
      #   run: terraform plan -no-color -input=false
"""

CI_WORKFLOW_PATH = ".github/workflows/terraform.yml"


def _md_escape(text: str | None) -> str:
    if not text:
        return ""
    return text.replace("|", "\\|").replace("\n", " ")


def build_readme(
    *,
    files: dict[str, str],
    cloud_provider: str = "aws",
    environment: str = "dev",
    resources_identified: list[str] | None = None,
    diagram_match_percent: int | None = None,
) -> str:
    res = hcl_summary.resources(files)
    data = hcl_summary.data_sources(files)
    variables = hcl_summary.variables(files)
    outputs = hcl_summary.outputs(files)
    tf_files = sorted(n for n in files if n.endswith(".tf"))

    lines: list[str] = []
    lines.append("# Infrastructure")
    lines.append("")
    lines.append(
        f"Terraform for a **{cloud_provider.upper()}** deployment "
        f"(`{environment}` environment), generated by "
        "[TerraSketch](https://terrasketch.onrender.com) as a first draft. "
        "Review it before applying."
    )
    lines.append("")

    # Quick start
    lines.append("## Quick start")
    lines.append("")
    lines.append("```bash")
    lines.append("terraform init")
    lines.append("terraform plan    # review the changes")
    lines.append("terraform apply   # create the resources")
    lines.append("```")
    lines.append("")
    lines.append(
        "Copy `terraform.tfvars.example` to `terraform.tfvars` and adjust values first."
    )
    lines.append("")

    # Files
    lines.append("## Files")
    lines.append("")
    for n in tf_files:
        lines.append(f"- `{n}`")
    lines.append("")

    # Resources
    if res or data:
        lines.append("## Resources")
        lines.append("")
        lines.append("| Address | Type |")
        lines.append("| --- | --- |")
        for t, name in res:
            lines.append(f"| `{t}.{name}` | resource |")
        for t, name in data:
            lines.append(f"| `data.{t}.{name}` | data source |")
        lines.append("")

    # Inputs
    if variables:
        lines.append("## Inputs")
        lines.append("")
        lines.append("| Name | Type | Default | Description |")
        lines.append("| --- | --- | --- | --- |")
        for v in variables:
            typ = f"`{_md_escape(v['type'])}`" if v["type"] else ""
            dflt = f"`{_md_escape(v['default'])}`" if v["default"] is not None else "_required_"
            lines.append(
                f"| `{v['name']}` | {typ} | {dflt} | {_md_escape(v['description'])} |"
            )
        lines.append("")

    # Outputs
    if outputs:
        lines.append("## Outputs")
        lines.append("")
        lines.append("| Name | Description |")
        lines.append("| --- | --- |")
        for o in outputs:
            lines.append(f"| `{o['name']}` | {_md_escape(o['description'])} |")
        lines.append("")

    if resources_identified:
        pct = f" (~{diagram_match_percent}% diagram match)" if diagram_match_percent else ""
        lines.append("## Notes")
        lines.append("")
        lines.append(
            "Identified from the source diagram/description"
            + pct
            + ": "
            + ", ".join(resources_identified)
            + "."
        )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by TerraSketch. This is a starting point — validate, "
                 "add remote state, and review security before production use._")
    lines.append("")
    return "\n".join(lines)


def build_example_tfvars(files: dict[str, str]) -> str:
    variables = hcl_summary.variables(files)
    lines = [
        "# Example variable values. Copy to terraform.tfvars and edit.",
        "# Lines with defaults are commented out — uncomment to override.",
        "",
    ]
    if not variables:
        lines.append("# (This configuration declares no input variables.)")
        return "\n".join(lines) + "\n"

    for v in variables:
        if v["description"]:
            lines.append(f"# {v['description']}")
        if v["default"] is not None:
            lines.append(f'# {v["name"]} = {v["default"]}')
        else:
            placeholder = "\"\"" if (v["type"] or "string") .startswith(("string", "\"")) else "null"
            lines.append(f"{v['name']} = {placeholder}  # required")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
