/**
 * Handoff helpers — make a generation "handoff-ready":
 *   1. buildAiBundle     → a prompt-ready markdown bundle for Cursor/Copilot/ChatGPT
 *   2. buildReadme       → a deterministic README.md documenting the stack
 *   3. pinProviderVersions → rewrite the terraform{} block with chosen versions
 *
 * All deterministic — no LLM, no backend.
 */

const PROVIDER_META = {
  aws: { name: "aws", source: "hashicorp/aws", label: "AWS", defaultVersion: "~> 5.0" },
  azure: { name: "azurerm", source: "hashicorp/azurerm", label: "Azure", defaultVersion: "~> 3.0" },
  gcp: { name: "google", source: "hashicorp/google", label: "GCP", defaultVersion: "~> 5.0" },
};

export function providerMeta(provider) {
  return PROVIDER_META[provider] || PROVIDER_META.aws;
}

const FILE_ORDER = ["main.tf", "variables.tf", "outputs.tf", "providers.tf"];

function matchNames(re, text) {
  const out = [];
  let m;
  while ((m = re.exec(text || "")) !== null) out.push(m[1]);
  return out;
}

// ── 1. Copy for AI tools ──────────────────────────────────────────────────────

export function buildAiBundle(data = {}, files = {}) {
  const meta = providerMeta(data.cloud_provider);
  const resources = data.resources_identified || [];
  const placeholders = data.placeholders || [];

  const lines = [
    "# Terraform first-draft (generated by TerraSketch)",
    "",
    `**Provider:** ${meta.label}  ·  **Environment:** ${data.environment || "dev"}`,
    "",
    "This is a ~60–70% complete Terraform base. Help me finish and extend it — " +
      "keep it secure, follow best practices, and replace the `<REPLACE_*>` placeholders.",
    "",
  ];
  if (resources.length) lines.push(`**Resources:** ${resources.join(", ")}`, "");
  if (placeholders.length) lines.push(`**Placeholders to replace:** ${placeholders.join(", ")}`, "");

  for (const name of FILE_ORDER) {
    const content = files[name];
    if (!content) continue;
    lines.push(`## ${name}`, "```hcl", content.trimEnd(), "```", "");
  }
  return lines.join("\n");
}

// ── 2. README.md ──────────────────────────────────────────────────────────────

export function buildReadme(data = {}, files = {}) {
  const meta = providerMeta(data.cloud_provider);
  const resources = data.resources_identified || [];
  const placeholders = data.placeholders || [];
  const varNames = matchNames(/variable\s+"([^"]+)"/g, files["variables.tf"]);
  const outputNames = matchNames(/output\s+"([^"]+)"/g, files["outputs.tf"]);

  const lines = [
    `# ${meta.label} infrastructure (${data.environment || "dev"})`,
    "",
    "Generated by [TerraSketch](https://terrasketch.onrender.com). This is a " +
      "**~60–70% complete first draft** — review every `<REPLACE_*>` placeholder and " +
      "`# TODO` before deploying.",
    "",
    "## Files",
    "",
    "| File | Purpose |",
    "| --- | --- |",
    "| `main.tf` | Resources |",
    "| `variables.tf` | Input variables |",
    "| `outputs.tf` | Outputs |",
    "| `providers.tf` | Provider & version config |",
    "",
  ];

  if (resources.length) {
    lines.push("## Resources", "", ...resources.map((r) => `- ${r}`), "");
  }
  if (varNames.length) {
    lines.push("## Variables", "", ...varNames.map((v) => `- \`${v}\``), "");
  }
  if (outputNames.length) {
    lines.push("## Outputs", "", ...outputNames.map((o) => `- \`${o}\``), "");
  }

  lines.push(
    "## Usage",
    "",
    "```bash",
    "terraform init",
    "terraform plan",
    "terraform apply",
    "```",
    ""
  );

  if (placeholders.length) {
    lines.push(
      "## Placeholders to replace",
      "",
      ...placeholders.map((p) => `- \`${p}\``),
      ""
    );
  }
  return lines.join("\n");
}

// ── 3. Provider version pinning ───────────────────────────────────────────────

function replaceTerraformBlock(text, newBlock) {
  const m = /terraform\s*\{/.exec(text || "");
  if (!m) return `${newBlock}\n\n${text || ""}`.trim() + "\n";
  const braceIdx = text.indexOf("{", m.index);
  let depth = 0;
  for (let i = braceIdx; i < text.length; i++) {
    if (text[i] === "{") depth++;
    else if (text[i] === "}") {
      depth--;
      if (depth === 0) return text.slice(0, m.index) + newBlock + text.slice(i + 1);
    }
  }
  return `${newBlock}\n\n${text}`;
}

/**
 * Return a providers.tf with the terraform{} block rewritten to pin the
 * Terraform core version and the provider version constraint.
 */
export function pinProviderVersions(providersTf = "", { provider, terraformVersion, providerVersion }) {
  const meta = providerMeta(provider);
  const block = [
    "terraform {",
    `  required_version = "${terraformVersion}"`,
    "",
    "  required_providers {",
    `    ${meta.name} = {`,
    `      source  = "${meta.source}"`,
    `      version = "${providerVersion}"`,
    "    }",
    "  }",
    "}",
  ].join("\n");
  return replaceTerraformBlock(providersTf, block);
}
