/**
 * Repackage a flat 4-file generation into a reusable Terraform module layout:
 *
 *   main.tf            ← root: calls the module, wires variables through
 *   variables.tf       ← root: input declarations (re-used from the module)
 *   outputs.tf         ← root: re-exports the module's outputs
 *   providers.tf       ← root: provider config (belongs at the root, not the module)
 *   modules/<name>/
 *     main.tf          ← the resources
 *     variables.tf
 *     outputs.tf
 *   README.md
 *
 * This is a deterministic transform of the generated files — no LLM call — so a
 * team can drop the stack in as a `module {}` and reuse it across environments.
 */

function names(re, text) {
  const out = [];
  let m;
  while ((m = re.exec(text || "")) !== null) out.push(m[1]);
  return out;
}

export function sanitizeModuleName(raw) {
  const cleaned = (raw || "stack")
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return cleaned || "stack";
}

export function buildModuleFiles(files = {}, rawName = "stack") {
  const name = sanitizeModuleName(rawName);
  const mainTf = files["main.tf"] || "";
  const variablesTf = files["variables.tf"] || "";
  const outputsTf = files["outputs.tf"] || "";
  const providersTf = files["providers.tf"] || "";

  const varNames = names(/variable\s+"([^"]+)"/g, variablesTf);
  const outputNames = names(/output\s+"([^"]+)"/g, outputsTf);

  const pad = varNames.length ? Math.max(...varNames.map((v) => v.length)) : 0;
  const moduleCall = [
    `module "${name}" {`,
    `  source = "./modules/${name}"`,
    ...(varNames.length ? [""] : []),
    ...varNames.map((v) => `  ${v.padEnd(pad)} = var.${v}`),
    `}`,
    "",
  ].join("\n");

  const rootOutputs = outputNames.length
    ? outputNames
        .map((o) => `output "${o}" {\n  value = module.${name}.${o}\n}`)
        .join("\n\n") + "\n"
    : "";

  const readme = [
    `# ${name} (Terraform module)`,
    "",
    "Generated by TerraSketch and repackaged as a reusable module.",
    "",
    "```hcl",
    `module "${name}" {`,
    `  source = "./modules/${name}"`,
    "  # set the variables declared in variables.tf",
    "}",
    "```",
    "",
    "Run `terraform init && terraform plan` from this directory. Review every",
    "`<REPLACE_*>` placeholder before applying — this is a ~60–70% first draft.",
    "",
  ].join("\n");

  const out = {
    "main.tf": moduleCall,
    "variables.tf": variablesTf,
    "providers.tf": providersTf,
    "README.md": readme,
    [`modules/${name}/main.tf`]: mainTf,
    [`modules/${name}/variables.tf`]: variablesTf,
    [`modules/${name}/outputs.tf`]: outputsTf,
  };
  if (rootOutputs) out["outputs.tf"] = rootOutputs;
  return out;
}
